import adminGrey from "@/assets/sidebar/adminGrey.svg";
import adminWhite from "@/assets/sidebar/adminWhite.svg";
import bankOpWhite from "@/assets/sidebar/bankingOpWhite.svg";
import bankOpGrey from "@/assets/sidebar/bankOpGrey.svg";
import customerServGrey from "@/assets/sidebar/customerServGrey.svg";
import customerServWhite from "@/assets/sidebar/customerServWhite.svg";
import dashboardGrey from "@/assets/sidebar/dashboardGrey.svg";
import dashboardWhite from "@/assets/sidebar/dashboardWhite.svg";
import depositGrey from "@/assets/sidebar/depositGrey.svg";
import depositWhite from "@/assets/sidebar/depositWhite.svg";
import loanGrey from "@/assets/sidebar/loanGrey.svg";
import loanWhite from "@/assets/sidebar/loanWhite.svg";
import placementsGrey from "@/assets/sidebar/placementsGrey.svg";
import reportsGrey from "@/assets/sidebar/reportsGrey.svg";
import setupGrey from "@/assets/sidebar/setupGrey.svg";
import setupWhite from "@/assets/sidebar/setupWhite.svg";

export const navBarLinks = [
  {
    label: "Dashboard",
    path: "/",
    icon: dashboardGrey,
    activeIcon: dashboardWhite,
    children: [],
  },
  {
    label: "Setup",
    path: "/setup",
    icon: setupGrey,
    activeIcon: setupWhite,
    children: [
      "Manage Banks",
      "Demand Deposit Setup",
      "Product Document",
      "Loan Product Setup",
      "Treasury Product Setup",
      "Manage Branch",
      "Commercial Banks",
      "Manage GL Nodes",
      "Manage GL Class",
      "Manage Country",
      "Manage Regions",
      "Manage States",
      "Manage Departments",
      "Manage Towns",
      "Transaction Type Setup",
      "Manage Cheque Books",
      "Manage Exceptions",
    ],
  },
  {
    label: "Admin",
    path: "/admin",
    icon: adminGrey,
    activeIcon: adminWhite,
    children: [
      "Manage Users",
      "Map GL",
      "Manage Role",
      "Reset User",
      "Change Password",
      "Manage Posting Limit",
      "Manage GL Account",
      "Authorization",
      "Inter-Branch Access",
      "Manage System Lock",
      "Manage Account Officer",
      "Map EFASS",
      "SMS & Email Alerts",
      "System Reconciliation",
      "Download Statement",
    ],
  },
  {
    label: "Customer Service",
    path: "/customer-service",
    icon: customerServGrey,
    activeIcon: customerServWhite,
    children: [
      "Manage Customer",
      "Corporate Customer Link",
      "Manage Account",
      "Manage Mandate",
      "Customer Balance",
      "Standing Instruction",
      "Bulk Range Cheque",
      "Manage Contact",
      "Manage Lien",
      "Reset Customer Account Record",
      "Cheque Book Edit",
      "Account Reactivation",
      "BVN Maintenance",
      "Edit Old Account",
      "Close Account",
      "Manage Account Charge",
      "Alert Maintenance",
      "Manage Target",
      "Customer Maintenance History",
      "Account Profile",
    ],
  },
  {
    label: "Banking Operation",
    path: "/banking-operation",
    icon: bankOpGrey,
    activeIcon: bankOpWhite,
    children: [
      "Bulk Upload",
      "Tellering",
      "GL to Cash",
      "Clearing",
      "Transfer",
      "Cash Deposit",
      "Cash Withdrawal",
      "Cheque Deposit",
      "Cheque Withdrawal",
      "Batch Posting",
      "View Clearing CHQ",
      "Charge Concession",
      "Withdraw Toward Uncleared",
      "Same Day Reversal",
      "Batch Upload",
      "Transaction Reversal",
      "Return Cheque Reversal",
      "Amortise",
      "Transaction Authorization",
    ],
  },
  {
    label: "Deposit",
    path: "/deposit",
    icon: depositGrey,
    activeIcon: depositWhite,
    children: [
      "Create Deposit Account",
      "TD Mandate",
      "TD Liquidation",
      "TD Rate Adjustment",
      "TD Rollover",
      "TD Reduction",
      "Deal Certificate",
      "TD Lien",
      "TD Status",
      "TD Summary",
      "TD Top Up",
      "TD WHT Schedule",
      "TD Payable Schedule",
      "TD Deal List",
      "TD Proof",
    ],
  },
  {
    label: "Loan",
    path: "/loan",
    icon: loanGrey,
    activeIcon: loanWhite,
    children: [
      "Loan Calculator",
      "Manage Loan Application",
      "Manage Loan Accounts",
      "Disburse Loan",
      "Manage Group Loan Application",
      "Group Loan Disbursement",
      "Overdraft",
      "Top-Up Loan",
      "Restructure Loan",
      "Liquidate Loan",
      "Edit Loan Settlement",
      "Loan Repayment Due",
      "Loan Schedule",
      "Loan Receivable",
      "Loan Insurance",
      "Manage Loan Limit",
      "Loan Risk Rating",
      "CBN Loan Reports",
    ],
  },
  {
    label: "Reports",
    path: "/reports",
    icon: reportsGrey,
    activeIcon: "",
    children: [],
  },
  {
    label: "Placements",
    path: "/placements",
    icon: placementsGrey,
    activeIcon: "",
    children: [],
  },
];

export const navBarLink = [
  {
    label: "Dashboard",
    path: "/",
    icon: dashboardGrey,
    activeIcon: dashboardWhite,
    children: [],
  },
  {
    label: "Setup",
    path: "/setup",
    icon: setupGrey,
    activeIcon: setupWhite,
    children: [
      "Manage Banks",
      "Demand Deposit Setup",
      "Product Document",
      "Loan Product Setup",
      "Treasury Product Setup",
      "Manage Branch",
      "Commercial Banks",
      "Manage GL Nodes",
      "Manage GL Class",
      "Manage Country",
      "Manage Regions",
      "Manage States",
      "Manage Departments",
      "Manage Towns",
      "Transaction Type Setup",
      "Manage Cheque Books",
      "Manage Exceptions",
    ],
  },
  {
    label: "Admin",
    path: "/admin",
    icon: adminGrey,
    activeIcon: adminWhite,
    children: [
      "Manage Users",
      "Map GL",
      "Manage Role",
      "Reset User",
      "Change Password",
      "Manage Posting Limit",
      "Manage GL Account",
      "Authorization",
      "Inter-Branch Access",
      "Manage System Lock",
      "Manage Account Officer",
      "Map EFASS",
      "SMS & Email Alerts",
      "System Reconciliation",
      "Download Statement",
    ],
  },
  {
    label: "Customer Service",
    path: "/customer-service",
    icon: customerServGrey,
    activeIcon: customerServWhite,
    children: [
      "Manage Customer",
      "Corporate Customer Link",
      "Manage Account",
      "Manage Mandate",
      "Customer Balance",
      "Standing Instruction",
      "Bulk Range Cheque",
      "Manage Contact",
      "Manage Lien",
      "Reset Customer Account Record",
      "Cheque Book Edit",
      "Account Reactivation",
      "BVN Maintenance",
      "Edit Old Account",
      "Close Account",
      "Manage Account Charge",
      "Alert Maintenance",
      "Manage Target",
      "Customer Maintenance History",
      "Account Profile",
    ],
  },
  {
    label: "Banking Operation",
    path: "/banking-operation",
    icon: bankOpGrey,
    activeIcon: bankOpWhite,
    children: [
      "Bulk Upload",
      "Tellering",
      "GL to Cash",
      "Clearing",
      "Transfer",
      "Cash Deposit",
      "Cash Withdrawal",
      "Cheque Deposit",
      "Cheque Withdrawal",
      "Batch Posting",
      "View Clearing CHQ",
      "Charge Concession",
      "Withdraw Toward Uncleared",
      "Same Day Reversal",
      "Batch Upload",
      "Transaction Reversal",
      "Return Cheque Reversal",
      "Amortise",
      "Transaction Authorization",
    ],
  },
  {
    label: "Deposit",
    path: "/deposit",
    icon: depositGrey,
    activeIcon: depositWhite,
    children: [
      "Create Deposit Account",
      "TD Mandate",
      "TD Liquidation",
      "TD Rate Adjustment",
      "TD Rollover",
      "TD Reduction",
      "Deal Certificate",
      "TD Lien",
      "TD Status",
      "TD Summary",
      "TD Top Up",
      "TD WHT Schedule",
      "TD Payable Schedule",
      "TD Deal List",
      "TD Proof",
    ],
  },
  {
    label: "Loan",
    path: "/loan",
    icon: loanGrey,
    activeIcon: loanWhite,
    children: [
      "Loan Calculator",
      "Manage Loan Application",
      "Manage Loan Accounts",
      "Disburse Loan",
      "Manage Group Loan Application",
      "Group Loan Disbursement",
      "Overdraft",
      "Top-Up Loan",
      "Restructure Loan",
      "Liquidate Loan",
      "Edit Loan Settlement",
      "Loan Repayment Due",
      "Loan Schedule",
      "Loan Receivable",
      "Loan Insurance",
      "Manage Loan Limit",
      "Loan Risk Rating",
      "CBN Loan Reports",
    ],
  },
  {
    label: "Reports",
    path: "/reports",
    icon: reportsGrey,
    activeIcon: "",
    children: [],
  },
  {
    label: "Placements",
    path: "/placements",
    icon: placementsGrey,
    activeIcon: "",
    children: [],
  },
];

export const menuStructure = {
  Dashboard: [],
  Setup: [
    {
      label: "Manage Banks",
      path: "/setup/manage-banks",
      right: "manage_banks",
    },
    {
      label: "Demand Deposit Setup",
      path: "/setup/demand-deposit-setup",
      right: "demand_deposit_setup",
    },
  ],
  Admin: [
    {
      label: "Manage Users",
      path: "/admin/manage-users",
      right: "manage_users",
    },
    {
      label: "Map GL",
      path: "/admin/map-gl",
      right: "map_gl",
    },
  ],
};

export const ModuleIcon = {
  Setup: setupGrey,
  Admin: adminGrey,
  "Customer Service": customerServGrey,
  "Banking Operation": bankOpWhite,
  Deposit: depositGrey,
  Loan: loanGrey,
  Reports: reportsGrey,
  Placements: placementsGrey,
};

export const userRights = [
  "manage_banks",
  "demand_deposit_setup",
  "manage_users",
  "map_gl",
];
